Added Note to Contributors
jondavid-black/AaC pull request #179
Opened 2022-01-06 15:25 UTC by BryanBailey11

please look over this note and let me know of any addition or changes you think need to be done. Thanks! I added the same note to both the Readme and the Code of Conduct.

2022-01-06 16:14 UTC, cvchaparro requested changes
Looks good, overall, just a few minor recommendations.

2022-01-06 16:14 UTC, cvchaparro commented on CODE_OF_CONDUCT.md
> +contributors at this time. We will reject any pull requests from untrusted sources.
```suggestion
contributions at this time. We will reject any pull requests from unknown sources.
```

2022-01-06 16:14 UTC, cvchaparro commented on README.md
> +# Note to Contributors
```suggestion

# Note to Contributors
```

2022-01-06 16:14 UTC, cvchaparro commented on README.md
> +contributors at this time. We will reject any pull requests from untrusted sources.
```suggestion
contributions at this time. We will reject any pull requests from unknown sources.
```

2022-01-07 15:41 UTC, cvchaparro approved these changes
Nice work!

2022-01-07 21:07 UTC, Coffee2Bits approved these changes
Looks good. 👍

2022-01-08 01:26 UTC, merged