Create an LSP testing and assertion framework
jondavid-black/AaC pull request #367
Opened 2022-06-13 00:19 UTC by cvchaparro

Closes #326

Changes:
- TBD

2022-06-22 16:22 UTC, Coffee2Bits requested changes
Looks good; I'm excited by how easy those LSP tests look now! 

I did leave some feedback and suggestions.

2022-06-22 16:22 UTC, Coffee2Bits commented on python/tests/lang/test_server.py
> +        await self.create_document("added.aac", TEST_DOCUMENT_ADDITIONAL_CONTENT)
I like the pattern of demonstrating that the definitions aren't in the context prior to being piped in via the LSP.
```suggestion
        self.assertIsNone(self.active_context.get_definition_by_name(TEST_ADDITIONAL_SCHEMA_NAME))             
        self.assertIsNone(self.active_context.get_definition_by_name(TEST_ADDITIONAL_MODEL_NAME))
        
        await self.create_document("added.aac", TEST_DOCUMENT_ADDITIONAL_CONTENT)
```

2022-06-23 22:40 UTC, cvchaparro commented on python/tests/lang/base_lsp_test_case.py
> +            InitializeParams(process_id=12345, root_uri=self.to_uri("root.aac"), capabilities=ClientCapabilities()),
It's interesting that this sparked me to look at the [`InitializeParams`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeParams) structure in the LSP spec and I see now that `root_uri` is deprecated in favor of `workspaceFolders`. I will replace it with that so we don't forget but I'm curious, now, where this even gets used? I seem to recall it being required at one point but we never did anything with it, to my knowledge.

2022-06-24 16:56 UTC, Coffee2Bits approved these changes
Good work!

2022-06-24 16:56 UTC, merged