359 implement new plugin interface infrastructure
jondavid-black/AaC pull request #394
Opened 2022-07-18 15:37 UTC by cvchaparro

Closes #359

Closes:
- TBD

2022-07-22 20:53 UTC, Coffee2Bits requested changes
Looks good, just some discussion/future stories and a number of suggestions to align the API to use the `list` collection like the rest of the API. 

Two more items that I couldn't really add as suggestions, but need to be addressed since you already did the heavy lifting converting the plugins:
1. Remove all the hookspecs except for `get_plugin`
2. Remove the `@hookimpl` decorator from the plugin functions except for `get_plugin`

Here is what the modified hookspecs.py file for 1. above should be:
```python
"""Defines the AaC plugin interface via Pluggy Hookspecs."""
from aac.plugins import hookspec
from aac.plugins.plugin import Plugin


@hookspec
def get_plugin() -> Plugin:
    """
    Returns information about the plugin.

    Returns:
        A collection of information about the plugin and what it contributes.
    """
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/gen_design_doc/__init__.py
> +    plugin.register_definitions(set(plugin_definitions))
```suggestion
    plugin.register_commands(get_commands())
    plugin.register_definitions(plugin_definitions)
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/gen_gherkin_behaviors/__init__.py
> +    plugin.register_definitions(set(plugin_definitions))
```suggestion
    plugin.register_commands(get_commands())
    plugin.register_definitions(plugin_definitions)
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/gen_json/__init__.py
> +    plugin.register_definitions(set(plugin_definitions))
```suggestion
    plugin.register_commands(get_commands())
    plugin.register_definitions(plugin_definitions)
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/gen_plant_uml/__init__.py
> +    plugin.register_definitions(set(plugin_definitions))
```suggestion
    plugin.register_commands(get_commands())
    plugin.register_definitions(plugin_definitions)
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/gen_plugin/__init__.py
> +    plugin.register_definitions(set(plugin_definitions))
```suggestion
    plugin.register_commands(get_commands())
    plugin.register_definitions(plugin_definitions)
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/gen_plugin/templates/first_party/__init__.py.jinja2
> +    plugin.register_definitions(set(plugin_definitions))
```suggestion
    plugin.register_commands(get_commands())
    plugin.register_definitions(plugin_definitions)
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/gen_plugin/templates/third_party/__init__.py.jinja2
> +    plugin.register_definitions(set(plugin_definitions))
```suggestion
    plugin.register_commands(get_commands())
    plugin.register_definitions(plugin_definitions)
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/gen_protobuf/__init__.py
> +    plugin.register_definitions(set(plugin_definitions))
```suggestion
    plugin.register_commands(get_commands())
    plugin.register_definitions(plugin_definitions)
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/help_dump/__init__.py
> +    plugin.register_commands(set(get_commands()))
```suggestion
    plugin.register_commands(get_commands())
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/material_model/__init__.py
> +    plugin.register_definitions(set(plugin_definitions))
```suggestion
    plugin.register_commands(get_commands())
    plugin.register_definitions(plugin_definitions)
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/plugin.py
> +from typing import Optional
```suggestion
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/plugin.py
> +    def get_commands(self) -> Optional[set[AacCommand]]:
```suggestion
    def get_commands(self) -> list[AacCommand]:
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/plugin.py
> +    def register_validations(self, validations: set[ValidatorPlugin]):
```suggestion
    def register_validations(self, validations: list[ValidatorPlugin]):
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/plugin.py
> +    def get_validations(self) -> Optional[set[ValidatorPlugin]]:
```suggestion
    def get_validations(self) -> list[ValidatorPlugin]:
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/plugin.py
> +    def register_definitions(self, definitions: set[Definition]):
```suggestion
    def register_definitions(self, definitions: list[Definition]):
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/plugin.py
> +    def get_definitions(self) -> Optional[set[Definition]]:
```suggestion
    def get_definitions(self) -> list[Definition]:
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/print_spec/__init__.py
> +    plugin.register_commands(set(get_commands()))
```suggestion
    plugin.register_commands(get_commands())
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/rest_api/__init__.py
> +    plugin.register_commands(set(get_commands()))
```suggestion
    plugin.register_commands(get_commands())
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/specifications/__init__.py
> +    plugin.register_definitions(set(plugin_definitions))
```suggestion
    plugin.register_commands(get_commands())
    plugin.register_definitions(plugin_definitions)
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/start_lsp/__init__.py
> +    plugin.register_commands(set(get_commands()))
```suggestion
    plugin.register_commands(get_commands())
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/validators/defined_references/__init__.py
> +    plugin.register_validations({register_validators()})
```suggestion
    plugin.register_definitions(plugin_definitions)
    plugin.register_validations([register_validators()])
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/validators/exclusive_fields/__init__.py
> +    plugin.register_validations({register_validators()})
```suggestion
    plugin.register_definitions(plugin_definitions)
    plugin.register_validations([register_validators()])
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/validators/reference_fields/__init__.py
> +    plugin.register_validations({register_validators()})
```suggestion
    plugin.register_definitions(plugin_definitions)
    plugin.register_validations([register_validators()])
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/validators/reference_targets/__init__.py
> +    plugin.register_validations({register_validators()})
```suggestion
    plugin.register_definitions(plugin_definitions)
    plugin.register_validations([register_validators()])
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/validators/required_fields/__init__.py
> +    plugin.register_validations({register_validators()})
```suggestion
    plugin.register_definitions(plugin_definitions)
    plugin.register_validations([register_validators()])
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/validators/root_keys/__init__.py
> +    plugin.register_validations({register_validators()})
```suggestion
    plugin.register_definitions(plugin_definitions)
    plugin.register_validations([register_validators()])
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/validators/subcomponent_type/__init__.py
> +    plugin.register_validations({register_validators()})
```suggestion
    plugin.register_definitions(plugin_definitions)
    plugin.register_validations([register_validators()])
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/src/aac/plugins/validators/validator_implementation/__init__.py
> +    plugin.register_validations({register_validators()})
```suggestion
    plugin.register_definitions(plugin_definitions)
    plugin.register_validations([register_validators()])
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/tests/plugins/test_contribution_points.py
> +        self.assertEqual(self.contributions.get_definitions_by_plugin_name(self.plugin_name), definitions)
```suggestion
        commands = [create_command(f"Test{i}") for i in range(self.num_items)]
        self.contributions.register_commands(self.plugin_name, commands)
        self.assertListEqual(self.contributions.get_commands_by_plugin_name(self.plugin_name), commands)

        validations = [create_validation(f"Test{i}", create_validation_definition(f"Validation{i}")) for i in range(self.num_items)]
        self.contributions.register_validations(self.plugin_name, validations)
        self.assertListEqual(self.contributions.get_validations_by_plugin_name(self.plugin_name), validations)

        definitions = [create_schema_definition(f"Test{i}") for i in range(self.num_items)]
        self.contributions.register_definitions(self.plugin_name, definitions)
        self.assertListEqual(self.contributions.get_definitions_by_plugin_name(self.plugin_name), definitions)
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/tests/plugins/test_gen_json.py
> +        self.assertEqual(plugin.contributions.get_commands(), set(commands))
```suggestion
        self.assertListEqual(plugin.contributions.get_commands(), commands)
```

2022-07-22 20:53 UTC, Coffee2Bits commented on python/tests/plugins/test_gen_json.py
> +        self.assertEqual(plugin.contributions.get_definitions(), set(definitions))
```suggestion
        self.assertListEqual(plugin.contributions.get_definitions(), definitions)
```

2022-07-23 05:04 UTC, cvchaparro commented on python/src/aac/cli/aac_command.py
> +        return hash(self.name)
I definitely think we need to have a discussion on this. I actually debated this for the `__hash__` function on `PluginContribution`. The thing that occurs to me if we incorporate argument hashes, etc is that we can end up with effectively duplicated items if we add an argument to a plugin command, etc. I created #397 discussion to brainstorm this more.

2022-07-23 05:05 UTC, cvchaparro commented on python/src/aac/plugins/contribution_points.py
> +
```suggestion

```

2022-07-23 05:06 UTC, cvchaparro commented on python/src/aac/plugins/contribution_points.py
> +    See ContributionType for the complete list of contribution types.
```suggestion

    See ContributionType for the complete list of contribution types.
```

2022-07-23 05:06 UTC, cvchaparro commented on python/src/aac/lang/definitions/definition.py
> +        return hash(self.name)
See https://github.com/jondavid-black/AaC/pull/394#discussion_r928078962

2022-07-24 16:47 UTC, cvchaparro commented on python/tests/plugins/test_contribution_points.py
> +        self.assertEqual(self.contributions.get_validations_by_plugin_name(self.plugin_name), validations)
```suggestion
        self.assertCountEqual(self.contributions.get_commands_by_plugin_name(self.plugin_name), commands)
        self.assertCountEqual(self.contributions.get_definitions_by_plugin_name(self.plugin_name), definitions)
        self.assertCountEqual(self.contributions.get_validations_by_plugin_name(self.plugin_name), validations)
```

2022-07-24 19:30 UTC, Coffee2Bits approved these changes
Looks good!

2022-07-24 21:09 UTC, merged