Alexcmonnet/i-want-the-rest-api-351
jondavid-black/AaC pull request #396
Opened 2022-07-22 17:50 UTC by Coffee2Bits

Closes #351

* Added REST endpoint for getting available plugin commands
* Added REST endpoint for executing AaC plugin commands
* Added filter to prevent long-running commands from being executed via the REST API

2022-07-22 21:34 UTC, cvchaparro requested changes
Nice work, overall. One thing I did notice, though, is that commands that should fail, don't seem to. Specifically, I ran `validate` on the `alarm_clock.yaml` file after making changes such that it should be invalid (i.e. changing `Clock` to `Klock` and removing `when` from the scenario) and it still returned a valid response/message. This doesn't seem to be an issue when running from the command line, however.

2022-07-22 22:11 UTC, Coffee2Bits commented on python/src/aac/plugins/rest_api/models/command_model.py
> +    result_message: str
Good call out!

2022-07-22 22:13 UTC, Coffee2Bits commented on python/src/aac/plugins/rest_api/models/command_model.py
> +    """Response model for returning the results/outcomes of commands requests."""
```suggestion
    """Response model for returning the results/outcomes of command requests."""
```

2022-07-22 22:13 UTC, Coffee2Bits commented on python/src/aac/plugins/rest_api/models/command_model.py
> +    """REST API Model for the AaC Command class."""
```suggestion
    """REST API Model for the AaC Command Argument class."""
```

2022-07-23 04:00 UTC, cvchaparro requested changes
After our conversation about restarting the Rest API to test unsuccessful commands, I was able to confirm everything was working but we should probably have some kind of statement somewhere saying that it's required since, without thinking about it and knowing that the language context won't update definitions that are already present, I could see that being confusing and leading to erroneous results.

The last thing I'd point out is that `aac_rest_app.py` and `test_rest_api.py` seem to have been reformatted (at least partially) due to, what I assume is the result of a mismatched line length. Can you fix that - i.e. revert those formatting changes - please?

2022-07-24 18:59 UTC, Coffee2Bits commented
> After our conversation about restarting the Rest API to test unsuccessful commands, I was able to confirm everything was working but we should probably have some kind of statement somewhere saying that it's required since, without thinking about it and knowing that the language context won't update definitions that are already present, I could see that being confusing and leading to erroneous results.
> 
> The last thing I'd point out is that `aac_rest_app.py` and `test_rest_api.py` seem to have been reformatted (at least partially) due to, what I assume is the result of a mismatched line length. Can you fix that - i.e. revert those formatting changes - please?

I've fixed the formatting. The files are currently formatted per the black settings. Confirmed no change when black was run against the files `python -m black --line-length=127 --diff --quiet ./tests/plugins/test_rest_api.py`

2022-07-25 00:54 UTC, cvchaparro approved these changes
Nice work!

2022-07-25 15:18 UTC, merged