Move the LSP server to a plugin and fix plugin_manager
jondavid-black/AaC pull request #416
Opened 2022-08-09 03:59 UTC by cvchaparro

Closes #410
Closes #407

Changes:
- Move the all the LSP functionality into a plugin so that AaC is decoupled from editor-specific code.
- Remove all hookspecs except for the `get_plugin` hook.
- Update `plugin_manager` such that it uses the `get_plugin` hook in all functions.
- Update all plugins so that they implement the `get_plugin` hook and do not implement any of the old hooks.
- Update `gen-plugin` to generate plugins using only the `get_plugin` hook.

2022-08-11 21:14 UTC, Coffee2Bits requested changes
Great work! Just one open-ended suggestion/change.

2022-08-11 21:14 UTC, Coffee2Bits commented on python/src/aac/plugins/validators/_common.py
> +    """Return the ValidatorPlugins based on the plugin definitions."""
I'm conflicted on this. The function name and return type both imply a list of validator plugins, but until we implement the ability to support multiple validators per plugin this function could easily lead users to incorrectly believe that they can implement multiple validators per plugin.

This note in the docstring should suffice for now, unless you'd prefer to alter the return type and use the following pattern in the plugins:
```python
plugin.register_validations([_get_plugin_validation()])
```


```suggestion
    """
    Return the ValidatorPlugins based on the plugin definitions.
    
    Beware, plugins currently only support one validator per plugin. 
    """
```

2022-08-11 21:25 UTC, cvchaparro commented on python/src/aac/plugins/validators/_common.py
> +    """
```suggestion
    """
    Return the ValidatorPlugins based on the plugin definitions.

    Beware, plugins currently only support one validator per plugin.
    """
```

2022-08-13 22:03 UTC, Coffee2Bits approved these changes
Looks good!

2022-08-14 15:30 UTC, merged