Adding Validation to the Extension type field
jondavid-black/AaC pull request #498
Opened 2022-11-29 20:06 UTC by Coffee2Bits

* Added `Type references exist` to `extension` so that the field `type` is a valid definition reference
* Fixed type hint

2022-12-05 22:37 UTC, Coffee2Bits commented
This validation was missing, so users weren't seeing any error indications when writing extensions that target undefined types -- which is now validated with this PR.

2022-12-14 01:00 UTC, cvchaparro requested changes
When I test this, I'm getting an error in `heirarchy.py` that I think can be resolved by changing this line:
https://github.com/jondavid-black/AaC/blob/06411ca10263b9350acdd250e8239154a16cb3aa/python/src/aac/lang/hierarchy.py#L25

to this:
```python
    while not found_self_defined_ancestor and ancestor_definition:
```

2022-12-14 17:49 UTC, cvchaparro commented on python/src/aac/plugins/validators/defined_references/_validate_references.py
> +                    name_lexeme = name_lexeme or Lexeme(SourceLocation(0, 0, 0, 0), definition_under_test.source.uri, definition_under_test.name)
Was a missing value for `name_lexeme` causing the error mentioned in my previous review? I'm wondering if there will be unexpected ramifications of using a default `SourceLocation` of the first position in the file.

2022-12-14 21:00 UTC, cvchaparro approved these changes

2022-12-14 23:21 UTC, merged