Validation - Boolean Primitive Type
jondavid-black/AaC pull request #503
Opened 2022-12-06 19:58 UTC by JustAChucklin

closes #487 
- [x] There is a new primitive type validation for booleans
- [x] If the boolean values are treated as strings:
  - [x] The boolean primitive validation ensures that instances of "boolean" are true/false string values.
  - [x] When the values are compared, the string values should be converted to lowercase then compared -- allowing the user to use case insensitive FALSE/true values.
- [x] If a user puts a non-boolean value in a boolean field, their validation fails with an appropriate error message.

2022-12-06 22:53 UTC, Coffee2Bits commented on python/src/aac/plugins/first_party/primitive_type_check/validators/bool_validator.py
> +    `This function is intended to be used in the Validation apparatus, and for this result
```suggestion
    This function is intended to be used in the Validation apparatus, and for this result
```

2022-12-06 22:53 UTC, Coffee2Bits commented on python/src/aac/plugins/first_party/primitive_type_check/validators/bool_validator.py
> +        `A ValidatorFinding if the value is not a boolean or None.
```suggestion
        A ValidatorFinding if the value is not a boolean or None.
```

2022-12-06 23:00 UTC, Coffee2Bits requested changes
Looks good! Just need to register the bool validation to the plugin in order for the validate function to pick it up.

You'll need:
```python
def _get_primitive_validations() -> list[PrimitiveValidationContribution]:
    return [
        int_validator.get_validator(),
        bool_validator.get_validator(),
    ]
```
Here: https://github.com/jondavid-black/AaC/blob/464c7909e05a8f8dfec74705efa6a8a9b078d234/python/src/aac/plugins/first_party/primitive_type_check/__init__.py#L23-L26

After that, you should be able to force the error with the validate CLI command on a bad model.

2022-12-07 17:31 UTC, JustAChucklin commented
Ok pushed the commit through...I think your comments have been addressed @Coffee2Bits

2022-12-08 18:21 UTC, merged